examples/TodoApp/Controllers/SessionController.cs
using System.Threading.Tasks;
using Luno;
using Luno.Exceptions;
using TodoApp.Extensions;
using TodoApp.Helper;
using TodoApp.Models;
using TodoApp.ViewModels;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;

namespace TodoApp.Controllers
{
	public class SessionController : BaseController
	{
		public SessionController(LunoClient lunoClient)
			 : base(lunoClient)
		{ }

		// GET: /Session/
		public IActionResult Index()
		{
			return RedirectToAction(nameof(Create));
		}

		// GET: /Session/Create
		public async Task<IActionResult> Create()
		{
			if (await SessionHelper.GetSessionAsync(this, LunoClient) != null)
				return RedirectToAction("Index", "Account");

			return View();
		}

		// POST: /Session/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(LoginViewModel model)
		{
			if (await SessionHelper.GetSessionAsync(this, LunoClient) != null)
				return RedirectToAction("Index", "Account");

			if (!ModelState.IsValid)
				return View(model);

			try
			{
				var response = await LunoClient.User.LoginAsync<Profile, SessionStorage>(model.Username, model.Password, expand: new[] { "user" });
				HttpContext.Session.SetObjectAsJson("session", response.Session);
			}
			catch (LunoApiException ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				return View(model);
			}

			return RedirectToAction("Index", "Home");
		}

		// GET: /Session/Destroy
		public async Task<IActionResult> Destroy()
		{
			var session = await SessionHelper.GetSessionAsync(this, LunoClient);
			if (session == null)
				return RedirectToAction("Index", "Home");

			await LunoClient.Session.DeleteAsync(session);
			HttpContext.Session.Remove("session");
			return RedirectToAction("Index", "Home");
		}
	}
}

examples/TodoApp/Views/Session/Create.cshtml
@using TodoApp.ViewModels
@{
	ViewData["Title"] = "Sign In";
}
@model LoginViewModel

<div class="container">
	<form asp-controller="Session" asp-action="Create" asp-anti-forgery="true" method="post"
		  class="col-md-7">
		<div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>

		<div class="form-group">
			<label asp-for="Username" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="Username" class="form-control" />
				<span asp-validation-for="Username" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<label asp-for="Password" class="col-md-2 control-label"></label>
			<div class="col-md-10">
				<input asp-for="Password" type="password" class="form-control" />
				<span asp-validation-for="Password" class="text-danger"></span>
			</div>
		</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Sign In" class="btn btn-default" />
			</div>
		</div>
	</form>
</div>